---
- name: Testing andrewrothstein.buf
  hosts: all
  tasks:
    - name: Installing andrewrothstein.buf
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'buf --version'
      ansible.builtin.command: /usr/local/bin/buf --version
      changed_when: false
      register: buf_test_output
    - name: Output of 'buf --version'
      ansible.builtin.debug:
        msg: '{{ buf_test_output.stdout }}'
