---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/buf --version
    register: buf_test_output
  - name: buf --version
    debug:
      msg: '{{ buf_test_output.stdout }}'
