---
- name: Resolving vars for {{ buf_app }}
  ansible.builtin.include_vars: app-vars.yml
- name: Downloading {{ buf_app_url }} to {{ buf_app_install_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ buf_app_url }}'
    dest: '{{ buf_app_install_exe }}'
    checksum: '{{ buf_app_checksum }}'
    mode: '755'
- name: Linking {{ buf_app_install_link }} to {{ buf_app_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ buf_app_install_exe }}'
    dest: '{{ buf_app_install_link }}'
    state: link
