---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for buf {{ buf_ver }} install...
  become: yes
  stat:
    path: '{{ buf_install_dir }}'
  changed_when: False
  register: buf_binary
- when: not buf_binary.stat.exists
  block:
    - name: download buf {{ buf_ver }}...
      become: yes
      become_user: root
      get_url:
        url: '{{ buf_url }}'
        dest: /tmp/{{ buf_archive }}
        mode: 0644
        checksum: '{{ buf_checksum }}'
    - name: mkdir {{ buf_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ buf_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive buf {{ buf_ver }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ buf_archive }}
        dest: '{{ buf_install_dir }}'
        creates: '{{ buf_install_dir }}/buf'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ buf_archive }}
        state: absent
- name: link executables...
  become: yes
  become_user: root
  with_items:
    - buf
    - protoc-gen-buf-check-breaking
    - protoc-gen-buf-check-lint
  file:
    src: '{{ buf_install_dir }}/buf/bin/{{ item }}'
    dest: '{{ buf_parent_install_dir }}/bin/{{ item }}'
    state: link
